
import localFont from "next/font/local";
import { Love_Ya_Like_A_Sister, Luckiest_Guy, Lunasima, Poppins } from "next/font/google"
import "./globals.css";
import Providers from "./providers.jsx";


const PoppinsFont = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const LunasimaFont = Lunasima({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-lunasima",
})

const LuckiestGuy = Luckiest_Guy({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-luckiest-guy",
})

const LoveYaLikeASisterFont = Love_Ya_Like_A_Sister({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-love",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${PoppinsFont.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>

  );
}
